apiVersion: v1
kind: ConfigMap
metadata:
  name: adminservice-configmap
  namespace: adminservice
data:
  APP_CLIENT_ID: "e0c093cd-70ac-43cd-b558-6b3398871bed"
  AZURE_CLIENT_SECRET: "NVV8Q~Ujkw6VGTcfUOnQet7WpD.W9-kpuidZ1cE~"
  TENANT_ID: "84c31ca0-ac3b-4eae-ad11-519d80233e6f"
  KEY_VAULT_URL: "https://mongodbatlasconnection.vault.azure.net/"
  OPENAPI_CLIENT_ID: "7a240826-ab39-41f3-ad74-3c603c57ded2"
